server:
  port: 8094
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000

spring:
  application:
    name: library-shopping-cart
  profiles:
    active: dev
  jpa:
    open-in-view: false   # pom不添加jpa包会报程序包javax.persistence不存在，项目中不用jpa相关功能，关闭项目启动时的jpa警告

mapper:
  mappers: com.aiolos.library.common.MyMapper
  not-empty: false        # 在进行数据库操作的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aiolos.library.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    org.springframework.data.convert.CustomConversions: error # 取消服务启动时的某些警告
    org.springframework.cloud.loadbalancer.config.BlockingLoadBalancerClientAutoConfiguration: error

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka/

# 配置Hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000   # 设置Hystrix超时时间，超过6秒触发降级

feign:
  hystrix:
    enabled: true

ribbon:
  # 当请求某个微服务5s没连接，超时后会进行重试，先重试连接自己当前的这个实例
  # 如果当前实例重连一次失败，则会切换到访问集群中的下一个微服务实例，切换次数最大为2次
  ConnectTimeout: 10000          # 创建连接的超时时间，单位：ms
  ReadTimeout: 10000             # 在连接创建好以后，调用接口的超时时间，单位：ms
  MaxAutoRetries: 3             # 最大重试次数
  MaxAutoRetriesNextServer: 2   # 集群上一个实例节点宕机后，切换到后面多少个微服务实例去重试
  eureka:
    enabled: true

library:
  jwt:
    secret: librarysecretsalt
    expire: 7
    cache-expire: 10